version: '3.5'

services:
  db:
    image: mcr.microsoft.com/mssql/server
    container_name: sqlserver2
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=1q2w3e4r@#$
    ports:
      - 1433:1433
